from __future__ import annotations

import asyncio
from datetime import date, datetime
from types import SimpleNamespace

from PIL import Image

from bot.services.asoul_web_render import (
    ASoulWebRenderer,
    asoul_live_web_url,
    notification_payload,
    page_html,
    schedule_payload,
)


def _item(hour: int, *, highlighted: bool = False):
    return SimpleNamespace(
        starts_at=datetime(2026, 8, 30, hour, 0),
        hosts=("心宜", "思诺"),
        content="夏末联动直播",
        label="联动",
        highlighted=highlighted,
        highlight_style="粉色" if highlighted else "",
    )


def test_schedule_payload_is_shared_by_web_and_capture_modes():
    payload = schedule_payload(
        "tomorrow",
        [(date(2026, 8, 30), [_item(20, highlighted=True)])],
        generated_at="2026-08-30 12:00",
    )

    assert payload["view"] == "tomorrow"
    assert payload["title"] == "明日直播"
    assert payload["event_count"] == 1
    assert payload["days"][0]["items"][0]["hosts"] == ["心宜", "思诺"]
    assert payload["days"][0]["items"][0]["highlighted"] is True

    interactive = page_html()
    capture = page_html(payload, capture=True)
    assert 'data-view="today"' in interactive
    assert "__ASOUL_PAYLOAD_JSON__" not in capture
    assert '<body class="capture-mode">' in capture
    assert ".capture-mode .interactive-bar { display: none !important; }" in capture
    assert "心宜直播信号" not in capture
    assert "xinyi-hero" not in capture
    assert "hardware-cluster" not in capture
    assert '<span class="xinyi-mark"' in capture
    assert '.xinyi-mark { display: none; }' in capture
    assert "枝江日历功能由爱驼提供技术支持" in capture
    assert "AK-BOT FUNCTION" in capture
    assert "AK bot · Generated by Secmon" in capture
    assert 'root.className = "capture-card schedule-capture"' in capture
    assert "isolation: isolate" in capture
    assert "background: transparent" in capture
    assert "z-index: 1" in capture
    assert 'class="schedule-rail"' in capture
    assert 'class="schedule-glow schedule-glow-a"' in capture
    assert "background: linear-gradient(140deg, #fff8fb, #fff 38%, #f0fbf9 66%, #f7f3ff 100%)" in capture
    assert "backdrop-filter: blur(18px)" in capture
    assert "border-radius: 12px 30px 12px 30px" in capture
    assert 'class="date-month"' in capture
    assert 'class="schedule-meta"' in capture
    assert ".schedule-card .schedule-row::after { display: none; }" in capture
    assert ".schedule-card .masthead::after { display: none; }" in capture
    assert "background: #17181c" not in interactive
    assert "repeating-linear-gradient(135deg, #f9dfe9" not in interactive
    assert "backdrop-filter: blur(22px) saturate(145%)" in interactive
    assert "background: linear-gradient(135deg, #f26f82, #8d67ce)" in interactive
    assert ".interactive-bar::after" in interactive


def test_public_schedule_layout_is_responsive_at_mobile_and_landscape_widths(tmp_path):
    payload = schedule_payload(
        "week",
        [
            (
                date(2026, 8, 30),
                [
                    SimpleNamespace(
                        starts_at=datetime(2026, 8, 30, 20, 0),
                        hosts=("心宜", "思诺"),
                        content="这是一条用于验证手机端不会逐字换行或挤出卡片的较长直播标题",
                        label="特别直播",
                        highlighted=True,
                        highlight_style="粉色",
                    )
                ],
            )
        ],
        generated_at="2026-08-30 12:00",
    )

    async def inspect_layout():
        renderer = ASoulWebRenderer(tmp_path)
        try:
            await renderer.warmup()
            results = []
            for width, height in ((375, 812), (667, 375)):
                await renderer._page.set_viewport_size({"width": width, "height": height})
                await renderer._page.set_content(page_html(payload), wait_until="load")
                results.append(
                    await renderer._page.evaluate(
                        """() => ({
                            clientWidth: document.documentElement.clientWidth,
                            scrollWidth: document.documentElement.scrollWidth,
                            contentWidths: [...document.querySelectorAll('.schedule-content')].map(node => node.getBoundingClientRect().width),
                            rowsInsideCard: [...document.querySelectorAll('.schedule-row')].every(node => {
                                const row = node.getBoundingClientRect();
                                const card = document.querySelector('.schedule-card').getBoundingClientRect();
                                return row.left >= card.left && row.right <= card.right;
                            }),
                            barInsideViewport: (() => {
                                const bar = document.querySelector('.interactive-bar').getBoundingClientRect();
                                return bar.left >= 0 && bar.right <= document.documentElement.clientWidth;
                            })(),
                            switcherInsideBar: (() => {
                                const bar = document.querySelector('.interactive-bar').getBoundingClientRect();
                                const switcher = document.querySelector('.view-switcher').getBoundingClientRect();
                                return switcher.left >= bar.left && switcher.right <= bar.right;
                            })(),
                            touchTargets: [...document.querySelectorAll('.view-switcher button')].map(node => node.getBoundingClientRect().height),
                        })"""
                    )
                )
            return results
        finally:
            await renderer.close()

    for result in asyncio.run(inspect_layout()):
        assert result["scrollWidth"] == result["clientWidth"]
        assert min(result["contentWidths"]) > 100
        assert result["rowsInsideCard"] is True
        assert result["barInsideViewport"] is True
        assert result["switcherInsideBar"] is True
        assert min(result["touchTargets"]) >= 44


def test_notification_payload_keeps_each_visual_kind_distinct():
    dynamic = notification_payload("dynamic", dynamic={"author": "心宜", "text": "动态"})
    video = notification_payload("video", video={"author": "思诺", "text": "新视频"})
    started = notification_payload("live", live={"phase": "start", "text": "开播"})
    ended = notification_payload("live", live={"phase": "end", "text": "下播"})
    comment = notification_payload(
        "【B站评论区回复】乃琳Queen\n在思诺snow的动态底下的回复\n回复正文\nhttps://t.bilibili.com/1",
        comment={
            "author": "乃琳Queen",
            "context": "在思诺snow的动态底下的回复",
            "text": "[暗中观察]回复正文",
            "rich_nodes": (
                '[{"type":"emoji","text":"[暗中观察]",'
                '"url":"https://example.test/emote.png"},{"type":"text","text":"回复正文"}]'
            ),
            "url": "https://t.bilibili.com/1",
        },
    )

    assert [dynamic["mode"], video["mode"], started["mode"], ended["mode"], comment["mode"]] == [
        "dynamic",
        "video",
        "live-start",
        "live-end",
        "comment",
    ]
    assert comment["details"] == {
        "author": "乃琳Queen",
        "context": "在思诺snow的动态底下的回复",
        "text": "[暗中观察]回复正文",
        "rich_nodes": (
            '[{"type":"emoji","text":"[暗中观察]",'
            '"url":"https://example.test/emote.png"},{"type":"text","text":"回复正文"}]'
        ),
        "url": "https://t.bilibili.com/1",
    }
    notification_html = page_html(dynamic, capture=True)
    assert 'class="notification-surface"' in notification_html
    assert 'class="notification-rail"' in notification_html
    assert 'class="notification-glow notification-glow-a"' in notification_html
    assert 'class="mode-seal"' in notification_html
    assert ".notification-card {" in notification_html
    assert ".notification-card .creator::after { display: none; }" in notification_html
    assert "background: linear-gradient(140deg, #fff8fb, #fff 38%, #f0fbf9 66%, #f7f3ff 100%)" in notification_html
    assert "filter: blur(78px)" in notification_html
    assert "backdrop-filter: blur(18px)" in notification_html
    assert "border-radius: 28px" in notification_html
    assert ".notification-card.dynamic .notification-kind" in notification_html
    assert ".notification-card.comment .notification-kind" in notification_html
    assert ".notification-card.video .notification-kind" in notification_html
    assert ".notification-card.live-start .notification-kind" in notification_html
    assert ".notification-card.live-end .notification-kind" in notification_html


def test_notification_media_localization_embeds_rich_emoji_nodes(tmp_path):
    source = Image.new("RGBA", (12, 12), "#ef5f8d")
    renderer = ASoulWebRenderer(tmp_path, media_loader=lambda _: source.copy())
    payload = notification_payload(
        "动态",
        dynamic={
            "rich_nodes": '[{"type":"text","text":"正文"},{"type":"emoji","text":"[表情]","url":"https://example.test/emoji.png"}]',
            "quote_rich_nodes": '[{"type":"emoji","text":"[引用表情]","url":"https://example.test/quote.png"}]',
        },
    )

    localized = renderer._localize_media(payload)

    assert "data:image/png;base64," in localized["details"]["rich_nodes"]
    assert "data:image/png;base64," in localized["details"]["quote_rich_nodes"]
    html = page_html(localized, capture=True)
    assert "function richNodes" in html
    assert 'image(node.url, "inline-emoji")' in html


def test_notification_renderer_outputs_all_five_aurora_kinds(tmp_path):
    async def render_all():
        renderer = ASoulWebRenderer(tmp_path)
        try:
            paths = [
                await renderer.render_notification(
                    "动态",
                    dynamic={"author": "测试 UP", "text": "新的枝江动态"},
                ),
                await renderer.render_notification(
                    "视频",
                    video={"author": "测试 UP", "text": "新的枝江视频"},
                ),
                await renderer.render_notification(
                    "开播",
                    live={"phase": "start", "author": "测试 UP", "text": "正在直播"},
                ),
                await renderer.render_notification(
                    "下播",
                    live={"phase": "end", "author": "测试 UP", "text": "直播结束"},
                ),
                await renderer.render_notification(
                    "【B站评论区回复】乃琳Queen\n在思诺snow的动态底下的回复\n回复正文\nhttps://t.bilibili.com/1"
                ),
            ]
            rail_count = await renderer._page.locator(".notification-rail").count()
            glow_count = await renderer._page.locator(".notification-glow").count()
            title = await renderer._page.title()
            return paths, rail_count, glow_count, title
        finally:
            await renderer.close()

    paths, rail_count, glow_count, title = asyncio.run(render_all())

    assert rail_count == 1
    assert glow_count == 3
    assert title == "评论区回复 · 枝江 B站推送"
    for path in paths:
        assert path.is_file() and path.stat().st_size > 10_000
        with Image.open(path) as image:
            assert image.width == 1080
            assert image.height > 450
            assert image.getbbox() is not None


def test_public_schedule_url_uses_bare_short_links():
    assert asoul_live_web_url("today") == "s.secmon.cn/r"
    assert asoul_live_web_url("tomorrow") == "s.secmon.cn/r"
    assert asoul_live_web_url("week") == "s.secmon.cn/r"


def test_html_renderer_outputs_content_without_interactive_controls(tmp_path):
    renderer = ASoulWebRenderer(tmp_path)
    payload = schedule_payload(
        "today",
        [(date(2026, 8, 30), [_item(18), _item(21)])],
        generated_at="2026-08-30 12:00",
    )
    async def render_and_close():
        try:
            return await renderer.render_payload(payload, "schedule_test")
        finally:
            await renderer.close()

    path = asyncio.run(render_and_close())

    assert path.is_file() and path.stat().st_size > 10_000
    with Image.open(path) as image:
        assert image.width == 1080
        assert image.height > 500
        assert image.getbbox() is not None


def test_warm_renderer_can_render_consecutive_payloads(tmp_path):
    async def render_twice():
        renderer = ASoulWebRenderer(tmp_path)
        try:
            first = await renderer.render_schedule(
                "today",
                [(date(2026, 8, 30), [_item(20)])],
                generated_at="2026-08-30 12:00",
            )
            second = await renderer.render_notification(
                "【B站视频】测试 UP\n第二次连续渲染",
                video={"author": "测试 UP", "text": "第二次连续渲染"},
            )
            return first, second
        finally:
            await renderer.close()

    first, second = asyncio.run(render_twice())
    assert first.is_file() and second.is_file()
    assert first.read_bytes() != second.read_bytes()


def test_schedule_sticker_is_selected_from_hosts_and_embedded_locally(tmp_path):
    sticker = tmp_path / "xinyi.png"
    Image.new("RGBA", (48, 48), "#ef5f8d").save(sticker)
    selected_hosts = []

    def select(hosts):
        selected_hosts.append(tuple(hosts))
        return sticker

    renderer = ASoulWebRenderer(tmp_path, sticker_selector=select)
    payload = schedule_payload(
        "today",
        [(date(2026, 8, 30), [_item(20)])],
        generated_at="2026-08-30 12:00",
    )

    localized = renderer.localize_schedule_stickers(payload)

    assert selected_hosts == [("心宜", "思诺")]
    assert localized["days"][0]["items"][0]["sticker_url"].startswith("data:image/png;base64,")
    assert "sticker_url" not in payload["days"][0]["items"][0]
