from __future__ import annotations

import asyncio
import json
import random
from datetime import date
from io import BytesIO
from pathlib import Path
from time import sleep, time_ns
from typing import Any, Iterable
from urllib.parse import urlsplit, urlunsplit
from urllib.request import Request, urlopen

from PIL import Image, ImageDraw, ImageFont
import qrcode

from bot.config import RESOURCE_DIR
from bot.services.emoji_text import EmojiTextDraw
from bot.services.character_marks import draw_heart_tail, draw_stitched_mascot
from bot.services.image_style import paste_horizontal_gradient, transparent_rounded_corners


class ASoulImageRenderer:
    """Pillow cards styled after the original A-SOUL plugin's schedule output."""

    WIDTH = 1080
    EDGE = 28
    LEFT = 56
    RIGHT = 56
    _WEEKDAYS = ("周一", "周二", "周三", "周四", "周五", "周六", "周日")
    _HIGHLIGHTS = {
        "粉色": ("#fff1f6", "#d9658b", "#f7d7e4"),
        "红色": ("#fff2ef", "#b84e45", "#efd0ca"),
        "白金色": ("#fffdf5", "#9c8050", "#eee2c8"),
    }

    def __init__(
        self,
        output_dir: Path,
        font_path: Path | None = None,
        sticker_dir: Path | None = None,
    ) -> None:
        self.output_dir = output_dir / "asoul"
        self.font_path = font_path
        self.sticker_dir = sticker_dir or RESOURCE_DIR / "asoul_stickers"
        self._fonts: dict[tuple[int, bool], ImageFont.ImageFont] = {}
        self._stickers: dict[str, list[Path]] | None = None
        self._remote_cache: dict[str, Image.Image] = {}

    async def render_schedule(self, target_day: date, title: str, items: Iterable[Any]) -> Path:
        return await asyncio.to_thread(
            self._render_schedule,
            target_day,
            title,
            list(items),
        )

    async def render_week_schedule(self, day_items: Iterable[tuple[date, Iterable[Any]]]) -> Path:
        prepared = [(target_day, list(items)) for target_day, items in day_items]
        return await asyncio.to_thread(self._render_week_schedule, prepared)

    async def render_bilibili_notification(
        self,
        text: str,
        live: dict[str, str] | None = None,
        dynamic: dict[str, str] | None = None,
        video: dict[str, str] | None = None,
    ) -> Path:
        return await asyncio.to_thread(self._render_bilibili_notification, text, live, dynamic, video)

    def _render_schedule(self, target_day: date, title: str, items: list[Any]) -> Path:
        return self._render_calendar(
            [(target_day, items)],
            f"{target_day:%Y-%m-%d} {title}",
            f"{title}排班",
        )

    def _render_week_schedule(self, day_items: list[tuple[date, list[Any]]]) -> Path:
        first = day_items[0][0] if day_items else date.today()
        return self._render_calendar(day_items, f"{first:%Y-%m-%d} 起 本周直播", "本周排班")

    def _render_calendar(
        self,
        day_items: list[tuple[date, list[Any]]],
        heading: str,
        subtitle: str,
    ) -> Path:
        layouts = [(target_day, self._day_layout(items)) for target_day, items in day_items]
        body_height = sum(layout["height"] for _, layout in layouts) + max(0, len(layouts) - 1) * 24
        header_height = 218
        footer_height = 48
        height = max(450, self.EDGE * 2 + header_height + body_height + footer_height + 24)
        image = Image.new("RGBA", (self.WIDTH, height), "#fff8fb")
        draw = EmojiTextDraw(image)
        self._draw_background(draw, height)
        draw.rounded_rectangle(
            (self.EDGE, self.EDGE, self.WIDTH - self.EDGE, height - self.EDGE),
            radius=32,
            fill="#fffefd",
            outline="#f5dce7",
            width=2,
        )
        self._draw_header(image, draw, heading, subtitle, sum(len(items) for _, items in day_items))
        y = self.EDGE + header_height + 24
        for target_day, layout in layouts:
            self._draw_day(draw, image, y, target_day, layout)
            y += layout["height"] + 24
        draw.text(
            (self.WIDTH - self.RIGHT - self._text_width("爱驼推送 / Generated by LEN", self._font(16)), height - 49),
            "爱驼推送 / Generated by LEN",
            font=self._font(16),
            fill="#a98a98",
        )
        draw_heart_tail(draw, 82, height - 43)
        return self._save(image, "schedule")

    def _draw_background(self, draw: ImageDraw.ImageDraw, height: int) -> None:
        draw.rectangle((0, 0, self.WIDTH, height), fill="#fff8fb")
        draw.rectangle((0, 0, 12, height), fill="#fff0f6")

    def _draw_header(self, image: Image.Image, draw: ImageDraw.ImageDraw, heading: str, subtitle: str, count: int) -> None:
        top = self.EDGE
        bottom = top + 218
        paste_horizontal_gradient(
            image,
            (self.EDGE, top, self.WIDTH - self.EDGE, bottom),
            "#f3a2bd",
            "#fff4f8",
            radius=32,
        )
        draw.rounded_rectangle((self.LEFT + 12, top + 40, self.LEFT + 160, top + 80), radius=18, fill="#ffffff")
        draw.text((self.LEFT + 31, top + 49), "A-SOUL LIVE", font=self._font(18), fill="#ee5e91")
        draw.text(
            (self.LEFT + 12, top + 97),
            self._ellipsize(heading, self._font(50, True), 800),
            font=self._font(50, True),
            fill="#352932",
        )
        draw.text((self.LEFT + 12, top + 166), subtitle, font=self._font(23), fill="#987c89")
        count_text = f"{count} 条安排"
        draw.text(
            (self.WIDTH - self.RIGHT - self._text_width(count_text, self._font(27)), top + 166),
            count_text,
            font=self._font(27),
            fill="#ee5e91",
        )
        draw_stitched_mascot(draw, self.WIDTH - self.RIGHT - 88, top + 10, 50)

    def _day_layout(self, items: list[Any]) -> dict[str, Any]:
        rows: list[dict[str, Any]] = []
        for item in items:
            sticker = self.select_schedule_sticker(getattr(item, "hosts", ()) or ())
            content_width = 514 if sticker else 704
            lines = self._wrap(str(getattr(item, "content", "")), self._font(29), content_width, 2)
            row_height = max(138, 76 + len(lines) * 39)
            rows.append({"item": item, "sticker": sticker, "lines": lines, "height": row_height})
        if not rows:
            return {"rows": [], "height": 170}
        return {"rows": rows, "height": 76 + sum(row["height"] for row in rows) + 18 * (len(rows) - 1) + 24}

    def _draw_day(
        self,
        draw: ImageDraw.ImageDraw,
        image: Image.Image,
        y: int,
        target_day: date,
        layout: dict[str, Any],
    ) -> None:
        height = int(layout["height"])
        draw.rounded_rectangle(
            (self.LEFT, y, self.WIDTH - self.RIGHT, y + height),
            radius=26,
            fill="#fffefd",
            outline="#f3dce6",
            width=2,
        )
        heading = f"{target_day.month}月{target_day.day}日  {self._WEEKDAYS[target_day.weekday()]}"
        draw.text((self.LEFT + 28, y + 24), heading, font=self._font(34, True), fill="#352932")
        count_text = f"{len(layout['rows'])} 条"
        draw.text(
            (self.WIDTH - self.RIGHT - 30 - self._text_width(count_text, self._font(21)), y + 34),
            count_text,
            font=self._font(21),
            fill="#ee5e91",
        )
        if not layout["rows"]:
            draw.text((self.LEFT + 30, y + 102), "还没有查到直播安排", font=self._font(28), fill="#a58996")
            return
        row_y = y + 76
        for row in layout["rows"]:
            self._draw_schedule_row(draw, image, row_y, row)
            row_y += int(row["height"]) + 18

    def _draw_schedule_row(self, draw: ImageDraw.ImageDraw, image: Image.Image, y: int, row: dict[str, Any]) -> None:
        item = row["item"]
        row_height = int(row["height"])
        highlighted = bool(getattr(item, "highlighted", False))
        fill, color, time_fill = self._HIGHLIGHTS.get(
            str(getattr(item, "highlight_style", "")),
            ("#fffafd", "#553843", "#ffe5ef"),
        )
        draw.rounded_rectangle(
            (self.LEFT + 22, y, self.WIDTH - self.RIGHT - 22, y + row_height),
            radius=22,
            fill=fill,
            outline="#f0dbe4" if not highlighted else color,
            width=2 if highlighted else 1,
        )
        draw.rounded_rectangle((self.LEFT + 46, y + 20, self.LEFT + 194, y + row_height - 20), radius=18, fill=time_fill)
        time_text = f"{item.starts_at:%H:%M}"
        self._draw_centered(draw, self.LEFT + 120, y + row_height // 2, time_text, self._font(31, True), color)
        content_x = self.LEFT + 230
        label = str(getattr(item, "label", "直播"))
        draw.rounded_rectangle(
            (content_x, y + 22, content_x + self._text_width(label, self._font(17, True)) + 28, y + 52),
            radius=15,
            fill=color,
        )
        draw.text((content_x + 14, y + 28), label, font=self._font(17, True), fill="#ffffff")
        hosts = " / ".join(getattr(item, "hosts", ()) or ()) or "待确认"
        draw.text((content_x, y + 61), self._ellipsize(hosts, self._font(21), 500), font=self._font(21), fill="#967987")
        lines = row["lines"] or ["直播内容待定"]
        line_y = y + 91
        for line in lines:
            draw.text((content_x, line_y), line, font=self._font(29), fill="#352932")
            line_y += 37
        if row["sticker"]:
            self._paste_sticker(image, row["sticker"], self.WIDTH - self.RIGHT - 204, y + 12, 160, row_height - 24)

    def _render_bilibili_notification(
        self,
        text: str,
        live: dict[str, str] | None = None,
        dynamic: dict[str, str] | None = None,
        video: dict[str, str] | None = None,
    ) -> Path:
        if live is not None:
            return self._render_live_notification(text, live)
        if dynamic is not None:
            return self._render_dynamic_notification(dynamic)
        if video is not None:
            return self._render_video_notification(video)
        lines = [line.strip() for line in str(text).splitlines() if line.strip()]
        title = "B站通知"
        if lines:
            header = lines[0]
            if header.startswith("【") and "】" in header:
                kind, author = header[1:].split("】", 1)
                title = f"{kind}  {author.strip()}".strip()
            else:
                title = header
        body = lines[1:] or ["暂无详情"]
        wrapped = [piece for line in body for piece in self._wrap(line, self._font(27), self.WIDTH - self.LEFT - self.RIGHT - 54, 3)]
        height = max(430, 292 + len(wrapped) * 40 + 60)
        image = Image.new("RGBA", (self.WIDTH, height), "#fff8fb")
        draw = EmojiTextDraw(image)
        draw.rounded_rectangle((18, 18, self.WIDTH - 18, height - 18), radius=28, fill="#fffefd", outline="#f3dce6", width=2)
        paste_horizontal_gradient(image, (52, 54, self.WIDTH - 52, 220), "#f3a2bd", "#fff5f9", radius=22)
        draw.rounded_rectangle((self.LEFT + 12, 74, self.LEFT + 258, 110), radius=18, fill="#ffffff")
        draw.text((self.LEFT + 31, 82), "A-SOUL BILIBILI", font=self._font(18), fill="#ee5e91")
        draw.text((self.LEFT + 12, 136), self._ellipsize(title, self._font(43, True), 790), font=self._font(43, True), fill="#352932")
        body_top = 254
        draw.rounded_rectangle((self.LEFT, body_top, self.WIDTH - self.RIGHT, height - 76), radius=18, fill="#fffafd", outline="#f2dde6", width=1)
        y = body_top + 28
        for line in wrapped:
            draw.text((self.LEFT + 26, y), line, font=self._font(27), fill="#463640")
            y += 40
        footer = "爱驼推送 / Bilibili"
        draw.text((self.WIDTH - self.RIGHT - self._text_width(footer, self._font(16)), height - 49), footer, font=self._font(16), fill="#a98a98")
        self._draw_live_corner_ribbons(draw, height)
        return self._save(image, "bilibili")

    def _render_dynamic_notification(self, dynamic: dict[str, str]) -> Path:
        author = str(dynamic.get("author") or "B站UP主")
        uid = str(dynamic.get("uid") or "")
        profile = str(dynamic.get("profile") or "")
        body = str(dynamic.get("text") or "（无文字内容）")
        quote_author = str(dynamic.get("quote_author") or "")
        quote_text = str(dynamic.get("quote_text") or "")
        reserve_title = str(dynamic.get("reserve_title") or "")
        reserve_subtitle = str(dynamic.get("reserve_subtitle") or "")
        reserve_action = str(dynamic.get("reserve_action") or "预约")
        emoji_labels = [label for label in str(dynamic.get("emoji_labels") or "").split("|") if label]
        emoji_urls = [url for url in str(dynamic.get("emoji_urls") or "").split("|") if url]
        content_width = self.WIDTH - 152
        rich_nodes = self._parse_dynamic_rich_nodes(dynamic.get("rich_nodes"))
        image_urls = self._parse_dynamic_image_urls(dynamic.get("image_urls"))
        quote_rich_nodes = self._parse_dynamic_rich_nodes(dynamic.get("quote_rich_nodes"))
        quote_image_urls = self._parse_dynamic_image_urls(dynamic.get("quote_image_urls"))
        images = self._load_dynamic_images(image_urls)
        quote_images = self._load_dynamic_images(quote_image_urls)
        body_lines = (
            self._layout_dynamic_nodes(rich_nodes, self._font(30), content_width - 68)
            if rich_nodes
            else self._layout_dynamic_body(
                body,
                list(zip(emoji_labels, emoji_urls, strict=False)),
                self._font(30),
                content_width - 68,
            )
        )
        quote_lines = (
            self._layout_dynamic_nodes(quote_rich_nodes, self._font(24), content_width - 98, emoji_size=28)
            if quote_rich_nodes
            else [
                [("text", character) for character in line]
                for line in self._wrap_preserving_linebreaks(quote_text, self._font(24), content_width - 98, None)
            ]
            if quote_text
            else []
        )
        if quote_image_urls and not quote_lines:
            quote_lines = [[("text", "转发内容附图")]]
        image_layout = self._dynamic_image_grid_layout(images, self.WIDTH - 224)
        quote_image_layout = self._dynamic_image_grid_layout(quote_images, self.WIDTH - 280)
        quote_image_height = self._dynamic_image_grid_height(quote_image_layout)
        quote_height = 62 + len(quote_lines) * 38 + (16 + quote_image_height if quote_image_height else 0) if quote_lines else 0
        reserve_title_lines = self._wrap_preserving_linebreaks(reserve_title, self._font(25, True), 610, None) if reserve_title else []
        reserve_subtitle_lines = self._wrap_preserving_linebreaks(reserve_subtitle, self._font(20), 610, None) if reserve_subtitle else []
        reserve_height = 34 + len(reserve_title_lines) * 34 + len(reserve_subtitle_lines) * 28 + 18
        image_height = self._dynamic_image_grid_height(image_layout)
        content_top = 274
        content_cursor = content_top + 86 + len(body_lines) * 52
        if image_height:
            content_cursor += 18 + image_height
        if quote_lines:
            content_cursor += 8 + quote_height
        if reserve_title_lines or reserve_subtitle_lines:
            content_cursor += 18 + reserve_height
        content_bottom = content_cursor + 34
        height = content_bottom + 96
        image = Image.new("RGBA", (self.WIDTH, height), "#fff8fb")
        draw = EmojiTextDraw(image)
        draw.rounded_rectangle((0, 0, self.WIDTH, height), radius=42, fill="#fffafd")
        draw.rounded_rectangle((36, 36, self.WIDTH - 36, height - 36), radius=26, outline="#f1dce6", width=2)
        paste_horizontal_gradient(
            image,
            (36, 36, self.WIDTH - 36, 230),
            "#f3a2bd",
            "#fff5f9",
            radius=20,
            outline="#f0dce5",
        )
        self._paste_circle(image, str(dynamic.get("avatar_url") or ""), 74, 76, 132, "#fde3ec")
        draw.text((234, 79), self._ellipsize(author, self._font(44, True), 520), font=self._font(44, True), fill="#ef5f8d")
        draw.text((236, 142), f"UID: {uid}" if uid else "Bilibili UP", font=self._font(23), fill="#747888")
        badge = "最新动态"
        badge_width = self._text_width(badge, self._font(24, True)) + 52
        badge_left = self.WIDTH - 86 - badge_width
        draw.rounded_rectangle((badge_left, 90, self.WIDTH - 86, 140), radius=24, fill="#ffdeeb")
        self._draw_centered(draw, badge_left + badge_width // 2, 115, badge, self._font(24, True), "#ef5f8d")
        if profile:
            draw.text((236, 182), self._ellipsize(profile, self._font(20), 694), font=self._font(20), fill="#8b8f9e")

        draw.rounded_rectangle((76, content_top, self.WIDTH - 76, content_bottom), radius=18, fill="#fffefe", outline="#f2dde6", width=1)
        draw.text((112, content_top + 34), "动态正文", font=self._font(25, True), fill="#dc6d92")
        y = content_top + 86
        for line in body_lines:
            x = 112
            for token_type, value in line:
                if token_type == "emoji":
                    self._paste_emoji(image, value, x, y - 4, 42)
                    x += 46
                else:
                    draw.text((x, y), value, font=self._font(30), fill="#df5f8d" if token_type == "link" else "#352c34")
                    x += self._text_width(value, self._font(30))
            y += 52
        content_cursor = y
        if image_height:
            image_top = content_cursor + 18
            self._draw_dynamic_image_grid(image, image_layout, 112, image_top)
            content_cursor = image_top + image_height
        if quote_lines:
            quote_top = content_cursor + 8
            quote_bottom = quote_top + quote_height
            draw.rounded_rectangle((112, quote_top, self.WIDTH - 112, quote_bottom), radius=14, fill="#fff8fb", outline="#f3dce6", width=1)
            quote_label = f"引用动态  {quote_author}" if quote_author else "引用动态"
            draw.text((140, quote_top + 18), self._ellipsize(quote_label, self._font(21, True), content_width - 128), font=self._font(21, True), fill="#9a6e86")
            quote_y = quote_top + 50
            for line in quote_lines:
                quote_x = 140
                for token_type, value in line:
                    if token_type == "emoji":
                        self._paste_emoji(image, value, quote_x, quote_y - 2, 28)
                        quote_x += 32
                    else:
                        draw.text((quote_x, quote_y), value, font=self._font(24), fill="#df5f8d" if token_type == "link" else "#6d5a65")
                        quote_x += self._text_width(value, self._font(24))
                quote_y += 38
            if quote_image_height:
                self._draw_dynamic_image_grid(
                    image,
                    quote_image_layout,
                    140,
                    quote_y + 8,
                )
            content_cursor = quote_bottom
        if reserve_title_lines or reserve_subtitle_lines:
            reserve_top = content_cursor + 18
            reserve_bottom = reserve_top + reserve_height
            draw.rounded_rectangle((112, reserve_top, self.WIDTH - 112, reserve_bottom), radius=16, fill="#fff7fa", outline="#f3d6e3", width=2)
            draw.text((140, reserve_top + 16), "直播预约", font=self._font(20, True), fill="#a56e85")
            reserve_y = reserve_top + 44
            for line in reserve_title_lines:
                draw.text((140, reserve_y), line, font=self._font(25, True), fill="#343946")
                reserve_y += 34
            for line in reserve_subtitle_lines:
                draw.text((140, reserve_y), line, font=self._font(20), fill="#7b8190")
                reserve_y += 28
            action_width = max(92, self._text_width(reserve_action, self._font(20, True)) + 40)
            action_left = self.WIDTH - 140 - action_width
            action_top = reserve_top + max(18, (reserve_height - 54) // 2)
            draw.rounded_rectangle((action_left, action_top, action_left + action_width, action_top + 54), radius=16, fill="#f26999")
            self._draw_centered(draw, action_left + action_width // 2, action_top + 27, reserve_action, self._font(20, True), "#ffffff")
        support = "本功能由爱驼提供技术支持"
        footer = "A海岸 Bot · Generated by Secmon"
        draw.text((100, height - 57), support, font=self._font(13), fill="#9ea4b4")
        self._draw_centered(draw, self.WIDTH // 2, height - 57, footer, self._font(16), "#8c809b")
        self._draw_live_corner_ribbons(draw, height)
        return self._save(image, "bilibili_dynamic")

    @staticmethod
    def _parse_dynamic_rich_nodes(value: object) -> list[dict[str, str]]:
        if not isinstance(value, str) or not value:
            return []
        try:
            raw_nodes = json.loads(value)
        except (TypeError, ValueError):
            return []
        if not isinstance(raw_nodes, list):
            return []
        nodes: list[dict[str, str]] = []
        for raw_node in raw_nodes:
            if not isinstance(raw_node, dict):
                continue
            node_type = str(raw_node.get("type") or "text")
            text = str(raw_node.get("text") or "")
            url = str(raw_node.get("url") or "")
            if node_type == "emoji" and url:
                nodes.append({"type": "emoji", "text": text, "url": url})
            elif node_type == "link" and text:
                nodes.append({"type": "link", "text": text, "url": url})
            elif text:
                nodes.append({"type": "text", "text": text})
        return nodes

    @staticmethod
    def _parse_dynamic_image_urls(value: object) -> list[str]:
        if not isinstance(value, str) or not value:
            return []
        try:
            raw_urls = json.loads(value)
        except (TypeError, ValueError):
            return []
        if not isinstance(raw_urls, list):
            return []
        return [str(url) for url in raw_urls if str(url).startswith(("https://", "http://"))]

    def _load_dynamic_images(self, urls: list[str]) -> list[Image.Image | None]:
        return [self._remote_image(url) for url in urls]

    @staticmethod
    def _scaled_image_height(source: Image.Image | None, width: int, fallback: int) -> int:
        if source is None or source.width <= 0 or source.height <= 0:
            return fallback
        return max(1, round(width * source.height / source.width))

    def _dynamic_image_grid_layout(
        self, images: list[Image.Image | None], available_width: int
    ) -> list[tuple[Image.Image | None, int, int, int, int]]:
        if not images:
            return []
        gap = 12
        columns = 1 if len(images) == 1 else min(3, len(images))
        tile_width = (available_width - gap * (columns - 1)) // columns
        layout: list[tuple[Image.Image | None, int, int, int, int]] = []
        cursor_y = 0
        for row_start in range(0, len(images), columns):
            row = images[row_start:row_start + columns]
            heights = [self._scaled_image_height(source, tile_width, tile_width) for source in row]
            row_height = max(heights)
            for column, (source, height) in enumerate(zip(row, heights, strict=True)):
                left = column * (tile_width + gap)
                layout.append((source, left, cursor_y, tile_width, height))
            cursor_y += row_height + gap
        return layout

    @staticmethod
    def _dynamic_image_grid_height(layout: list[tuple[Image.Image | None, int, int, int, int]]) -> int:
        if not layout:
            return 0
        return max(top + height for _, _, top, _, height in layout)

    def _draw_dynamic_image_grid(
        self,
        image: Image.Image,
        layout: list[tuple[Image.Image | None, int, int, int, int]],
        left: int,
        top: int,
    ) -> None:
        if not layout:
            return
        draw = ImageDraw.Draw(image)
        for source, offset_x, offset_y, width, height in layout:
            box = (left + offset_x, top + offset_y, left + offset_x + width, top + offset_y + height)
            draw.rounded_rectangle(box, radius=16, fill="#f6eff4")
            self._paste_full_image(image, source, box)

    def _layout_dynamic_nodes(
        self,
        nodes: list[dict[str, str]],
        font: ImageFont.ImageFont,
        max_width: int,
        emoji_size: int = 42,
    ) -> list[list[tuple[str, str]]]:
        lines: list[list[tuple[str, str]]] = [[]]
        current_width = 0
        for node in nodes:
            if node.get("type") == "emoji":
                if current_width and current_width + emoji_size > max_width:
                    lines.append([])
                    current_width = 0
                lines[-1].append(("emoji", str(node["url"])))
                current_width += emoji_size + 4
                continue
            for character in str(node.get("text") or ""):
                if character == "\n":
                    lines.append([])
                    current_width = 0
                    continue
                token_width = self._text_width(character, font)
                if current_width and current_width + token_width > max_width:
                    lines.append([])
                    current_width = 0
                lines[-1].append(("link" if node.get("type") == "link" else "text", character))
                current_width += token_width
        return lines if any(lines) else [[("text", "（无文字内容）")]]

    def _layout_dynamic_body(
        self,
        text: str,
        emoji_assets: list[tuple[str, str]],
        font: ImageFont.ImageFont,
        max_width: int,
    ) -> list[list[tuple[str, str]]]:
        lines: list[list[tuple[str, str]]] = [[]]
        current_width = 0
        remaining = list(emoji_assets)
        index = 0
        while index < len(text):
            if text[index] == "\n":
                lines.append([])
                current_width = 0
                index += 1
                continue
            matched = next(
                ((position, label, url) for position, (label, url) in enumerate(remaining) if text.startswith(label, index)),
                None,
            )
            if matched is not None:
                position, label, url = matched
                token_width = 42
                if current_width and current_width + token_width > max_width:
                    lines.append([])
                    current_width = 0
                lines[-1].append(("emoji", url))
                current_width += token_width + 4
                remaining.pop(position)
                index += len(label)
                continue
            character = text[index]
            token_width = self._text_width(character, font)
            if current_width and current_width + token_width > max_width:
                lines.append([])
                current_width = 0
            lines[-1].append(("text", character))
            current_width += token_width
            index += 1
        return [line for line in lines if line] or [[("text", "（无文字内容）")]]

    def _render_video_notification(self, video: dict[str, str]) -> Path:
        author = str(video.get("author") or "B站UP主")
        uid = str(video.get("uid") or "")
        profile = str(video.get("profile") or "")
        title = str(video.get("text") or "（无标题）")
        description = str(video.get("description") or "").strip()
        video_url = str(video.get("url") or "")
        title_lines = self._wrap(title, self._font(42, True), 900, 2)
        description_lines = self._wrap_preserving_linebreaks(description, self._font(22), 844, 12) if description else []
        title_y = 274
        cover_top = 350 + max(0, len(title_lines) - 1) * 54
        cover_width = self.WIDTH - 152
        cover = self._remote_image(str(video.get("cover_url") or ""))
        cover_bottom = cover_top + self._scaled_image_height(cover, cover_width, 480)
        description_top = cover_bottom + 28
        description_height = 62 + len(description_lines) * 32 if description_lines else 0
        stats_top = description_top + description_height + (28 if description_lines else 22)
        height = stats_top + 250
        image = Image.new("RGBA", (self.WIDTH, height), "#fff8fb")
        draw = EmojiTextDraw(image)
        draw.rounded_rectangle((0, 0, self.WIDTH, height), radius=42, fill="#fffafd")
        draw.rounded_rectangle((36, 36, self.WIDTH - 36, height - 36), radius=26, outline="#f1dce6", width=2)
        paste_horizontal_gradient(
            image,
            (36, 24, self.WIDTH - 36, 230),
            "#f3a2bd",
            "#fff5f9",
            radius=20,
            outline="#f0dce5",
        )

        self._paste_circle(image, str(video.get("avatar_url") or ""), 74, 76, 132, "#fde3ec")
        draw.text((234, 79), self._ellipsize(author, self._font(44, True), 520), font=self._font(44, True), fill="#ef5f8d")
        draw.text((236, 142), f"UID: {uid}" if uid else "Bilibili UP", font=self._font(23), fill="#747888")
        badge = "最新视频"
        badge_width = self._text_width(badge, self._font(24, True)) + 52
        badge_left = self.WIDTH - 86 - badge_width
        draw.rounded_rectangle((badge_left, 90, self.WIDTH - 86, 140), radius=24, fill="#ffdeeb")
        self._draw_centered(draw, badge_left + badge_width // 2, 115, badge, self._font(24, True), "#ef5f8d")
        if profile:
            draw.text((236, 182), self._ellipsize(profile, self._font(20), 694), font=self._font(20), fill="#8b8f9e")

        for index, line in enumerate(title_lines):
            draw.text((76, title_y + index * 54), line, font=self._font(42, True), fill="#242734")
        cover_box = (76, cover_top, self.WIDTH - 76, cover_bottom)
        draw.rounded_rectangle(cover_box, radius=22, fill="#f6eff4")
        if cover is None:
            self._draw_centered(draw, self.WIDTH // 2, (cover_top + cover_bottom) // 2, "Bilibili Video", self._font(38, True), "#81889a")
        else:
            self._paste_full_image(image, cover, cover_box)

        if description_lines:
            draw.rounded_rectangle(
                (76, description_top, self.WIDTH - 76, description_top + description_height),
                radius=18,
                fill="#fffafd",
                outline="#f2dde6",
                width=1,
            )
            draw.text((108, description_top + 17), "视频简介", font=self._font(20, True), fill="#8c7280")
            description_y = description_top + 47
            for line in description_lines:
                draw.text((108, description_y), line, font=self._font(22), fill="#616778")
                description_y += 32

        draw.rounded_rectangle((76, stats_top, self.WIDTH - 76, height - 76), radius=22, fill="#fffafd", outline="#f2dde6", width=1)
        stats = (
            ("获赞", self._format_stat(video.get("likes"))),
            ("关注", self._format_stat(video.get("following"))),
            ("粉丝", self._format_stat(video.get("followers"))),
        )
        for index, (label, value) in enumerate(stats):
            left = 108 + index * 192
            draw.rounded_rectangle((left, stats_top + 30, left + 166, stats_top + 130), radius=16, fill="#fffafd")
            draw.text((left + 18, stats_top + 47), label, font=self._font(20), fill="#8d94a4")
            draw.text((left + 18, stats_top + 79), value, font=self._font(27, True), fill="#3f4554")
        qr = self._qr_image(video_url, 128)
        if qr is not None:
            qr_left = self.WIDTH - 76 - 158
            image.alpha_composite(qr, (qr_left + 15, stats_top + 17))

        support = "本功能由爱托提供技术支持"
        footer = "A海岸 Bot · Generated by Secmon"
        draw.text((100, height - 57), support, font=self._font(13), fill="#9ea4b4")
        self._draw_centered(draw, self.WIDTH // 2, height - 57, footer, self._font(16), "#8c809b")
        self._draw_live_corner_ribbons(draw, height)
        return self._save(image, "bilibili_video")

    def _render_live_notification(self, text: str, live: dict[str, str]) -> Path:
        lines = [line.strip() for line in str(text).splitlines() if line.strip()]
        starting = str(live.get("phase") or "start") == "start"
        author = str(live.get("author") or (lines[0].split("】", 1)[-1] if lines else "B站UP主"))
        title = str(live.get("text") or (lines[1] if len(lines) > 1 else "直播间"))
        room_url = str(live.get("url") or (lines[2] if len(lines) > 2 else ""))
        uid = str(live.get("uid") or "")
        profile = str(live.get("profile") or "")
        cover_width = self.WIDTH - 152
        cover = self._remote_image(str(live.get("cover_url") or ""))
        cover_top = 360
        cover_height = self._scaled_image_height(cover, cover_width, 500 if starting else 430)
        cover_bottom = cover_top + cover_height
        height = cover_bottom + (300 if starting else 750)
        image = Image.new("RGBA", (self.WIDTH, height), "#fff8fb")
        draw = EmojiTextDraw(image)
        draw.rounded_rectangle((0, 0, self.WIDTH, height), radius=42, fill="#fffafd")
        draw.rounded_rectangle((36, 36, self.WIDTH - 36, height - 36), radius=26, outline="#f1dce6", width=2)
        paste_horizontal_gradient(
            image,
            (36, 24, self.WIDTH - 36, 230),
            "#f3a2bd",
            "#fff5f9",
            radius=20,
            outline="#f0dce5",
        )

        self._paste_circle(image, str(live.get("avatar_url") or ""), 74, 76, 132, "#fde3ec")
        draw.text((234, 79), self._ellipsize(author, self._font(44, True), 520), font=self._font(44, True), fill="#ef5f8d")
        uid_text = f"UID: {uid}" if uid else "Bilibili UP"
        draw.text((236, 142), uid_text, font=self._font(23), fill="#747888")
        badge = "正在直播" if starting else "直播已结束"
        badge_width = self._text_width(badge, self._font(24, True)) + 52
        badge_left = self.WIDTH - 86 - badge_width
        draw.rounded_rectangle((badge_left, 90, self.WIDTH - 86, 140), radius=24, fill="#ffdeeb" if starting else "#e7eaf2")
        self._draw_centered(draw, badge_left + badge_width // 2, 115, badge, self._font(24, True), "#ef5f8d" if starting else "#626978")
        if profile:
            draw.text((236, 182), self._ellipsize(profile, self._font(20), 694), font=self._font(20), fill="#8b8f9e")

        draw.text((76, 274), self._ellipsize(title, self._font(46, True), 900), font=self._font(46, True), fill="#242734")
        cover_box = (76, cover_top, self.WIDTH - 76, cover_bottom)
        draw.rounded_rectangle(cover_box, radius=22, fill="#f6eff4")
        if cover is None:
            self._draw_centered(draw, self.WIDTH // 2, (cover_top + cover_bottom) // 2, "Bilibili Live", self._font(38, True), "#81889a")
        else:
            self._paste_full_image(image, cover, cover_box)

        if starting and room_url:
            profile_top = cover_bottom + 50
            draw.rounded_rectangle((76, profile_top, self.WIDTH - 76, height - 76), radius=22, fill="#fffafd", outline="#f2dde6", width=1)
            stats = (("获赞", self._format_stat(live.get("likes"))), ("关注", self._format_stat(live.get("following"))), ("粉丝", self._format_stat(live.get("followers"))))
            for index, (label, value) in enumerate(stats):
                left = 108 + index * 192
                draw.rounded_rectangle((left, profile_top + 30, left + 166, profile_top + 130), radius=16, fill="#fffafd")
                draw.text((left + 18, profile_top + 47), label, font=self._font(20), fill="#8d94a4")
                draw.text((left + 18, profile_top + 79), value, font=self._font(27, True), fill="#3f4554")
            qr = self._qr_image(room_url, 128)
            if qr is not None:
                qr_left = self.WIDTH - 76 - 158
                qr_x = qr_left + 15
                image.alpha_composite(qr, (qr_x, profile_top + 17))
        elif not starting:
            settlement_top = cover_bottom + 48
            draw.rounded_rectangle((76, settlement_top, 336, settlement_top + 58), radius=24, fill="#fce0eb")
            self._draw_heart(draw, 111, settlement_top + 28, 15, "#ef5f8d")
            draw.text((140, settlement_top + 14), "直播结算", font=self._font(27, True), fill="#d95080")
            settlement_note = "数据为糖糖每 5 分钟观测，非 B 站官方结算"
            draw.text(
                (360, settlement_top + 20),
                self._ellipsize(settlement_note, self._font(16), self.WIDTH - 436),
                font=self._font(16),
                fill="#9ea4b4",
            )
            duration = str(live.get("live_duration") or "未完整观测")
            peak = str(live.get("popularity_peak") or "--")
            average = str(live.get("popularity_average") or "--")
            likes_delta = str(live.get("likes_delta") or "--")
            following_delta = str(live.get("following_delta") or "--")
            followers_delta = str(live.get("followers_delta") or "--")
            summary_top = settlement_top + 84
            duration_left = 76
            duration_right = 382
            popularity_left = 412
            popularity_right = self.WIDTH - 76
            draw.rounded_rectangle(
                (duration_left, summary_top, duration_right, summary_top + 206),
                radius=24,
                fill="#fff0f6",
                outline="#f4d8e5",
                width=2,
            )
            self._draw_centered(
                draw,
                (duration_left + duration_right) // 2,
                summary_top + 51,
                "直播时长",
                self._font(22, True),
                "#ad8192",
            )
            self._draw_centered(
                draw,
                (duration_left + duration_right) // 2,
                summary_top + 132,
                self._ellipsize(duration, self._font(42, True), duration_right - duration_left - 36),
                self._font(42, True),
                "#2c3040",
            )
            draw.rounded_rectangle(
                (popularity_left, summary_top, popularity_right, summary_top + 206),
                radius=24,
                fill="#fffafd",
                outline="#eee1e9",
                width=2,
            )
            draw.text((popularity_left + 32, summary_top + 25), "直播间人气", font=self._font(22, True), fill="#596173")
            popularity_mid = (popularity_left + popularity_right) // 2
            draw.line((popularity_mid, summary_top + 75, popularity_mid, summary_top + 176), fill="#eee6ed", width=2)
            self._draw_centered(draw, (popularity_left + popularity_mid) // 2, summary_top + 99, "峰值", self._font(21, True), "#8e94a3")
            self._draw_centered(draw, (popularity_left + popularity_mid) // 2, summary_top + 151, peak, self._font(39, True), "#303643")
            self._draw_centered(draw, (popularity_mid + popularity_right) // 2, summary_top + 99, "均值", self._font(21, True), "#8e94a3")
            self._draw_centered(draw, (popularity_mid + popularity_right) // 2, summary_top + 151, average, self._font(39, True), "#303643")

            growth_top = summary_top + 258
            draw.text((76, growth_top), "累计新增", font=self._font(29, True), fill="#3d4353")
            draw.line((76, growth_top + 47, self.WIDTH - 76, growth_top + 47), fill="#e9e1e8", width=2)
            growth_columns = (("获赞", likes_delta, "#ed6b94"), ("关注", following_delta, "#7d9fd0"), ("粉丝", followers_delta, "#a882c7"))
            for index, (label, value, color) in enumerate(growth_columns):
                center_x = 220 + index * 320
                self._draw_centered(draw, center_x, growth_top + 92, label, self._font(22, True), "#8e94a3")
                self._draw_centered(draw, center_x, growth_top + 151, value, self._font(48, True), color)
        support = "本功能由爱托提供技术支持"
        footer = "A海岸 Bot · Generated by Secmon"
        draw.text((100, height - 57), support, font=self._font(13), fill="#9ea4b4")
        self._draw_centered(draw, self.WIDTH // 2, height - 57, footer, self._font(16), "#8c809b")
        self._draw_live_corner_ribbons(draw, height)
        return self._save(image, "bilibili")

    def _draw_live_corner_ribbons(self, draw: ImageDraw.ImageDraw, height: int) -> None:
        """Quiet registration marks replace the old rainbow corner rails."""
        inset, span = 18, 78
        draw.line((inset, inset + span, inset, inset, inset + span, inset), fill="#ff91b4", width=7, joint="curve")
        draw.line(
            (self.WIDTH - inset - 42, inset, self.WIDTH - inset, inset, self.WIDTH - inset, inset + 26),
            fill="#f7c8d8",
            width=3,
            joint="curve",
        )
        draw.line((inset, height - inset - 26, inset, height - inset, inset + 44, height - inset), fill="#f7c8d8", width=3, joint="curve")
        draw_stitched_mascot(draw, self.WIDTH - 136, 0, 52)
        self._draw_bunny(draw, self.WIDTH - 66, height - 62, 18)
        self._draw_cross(draw, self.WIDTH - 47, 49, 9)
        self._draw_bandage(draw, 72, height - 72)
        draw_heart_tail(draw, 82, height - 43)

    def _draw_bunny(self, draw: ImageDraw.ImageDraw, center_x: int, center_y: int, size: int) -> None:
        ink = "#dc789c"
        draw.ellipse((center_x - size, center_y - size // 2, center_x + size, center_y + size + size // 2), fill="#fffafd", outline=ink, width=2)
        draw.ellipse((center_x - size + 2, center_y - size * 2, center_x - 1, center_y + 2), fill="#fffafd", outline=ink, width=2)
        draw.ellipse((center_x + 1, center_y - size * 2, center_x + size - 2, center_y + 2), fill="#fffafd", outline=ink, width=2)
        draw.ellipse((center_x - size // 2 - 2, center_y + size // 2, center_x - size // 2 + 2, center_y + size // 2 + 4), fill=ink)
        draw.ellipse((center_x + size // 2 - 2, center_y + size // 2, center_x + size // 2 + 2, center_y + size // 2 + 4), fill=ink)
        draw.arc((center_x - 5, center_y + size, center_x + 5, center_y + size + 8), 0, 180, fill=ink, width=1)

    @staticmethod
    def _draw_cross(draw: ImageDraw.ImageDraw, center_x: int, center_y: int, size: int) -> None:
        draw.line((center_x - size, center_y - size, center_x + size, center_y + size), fill="#f081a5", width=3)
        draw.line((center_x + size, center_y - size, center_x - size, center_y + size), fill="#f081a5", width=3)

    @staticmethod
    def _draw_bandage(draw: ImageDraw.ImageDraw, center_x: int, center_y: int) -> None:
        draw.polygon(
            [(center_x - 22, center_y - 7), (center_x - 14, center_y - 15), (center_x + 22, center_y + 7), (center_x + 14, center_y + 15)],
            fill="#ffd5e2",
        )
        draw.rounded_rectangle((center_x - 5, center_y - 5, center_x + 5, center_y + 5), radius=3, fill="#f291b1")

    @staticmethod
    def _draw_heart(draw: ImageDraw.ImageDraw, center_x: int, center_y: int, size: int, fill: str) -> None:
        radius = max(3, size // 4)
        draw.ellipse((center_x - radius * 2, center_y - radius, center_x, center_y + radius), fill=fill)
        draw.ellipse((center_x, center_y - radius, center_x + radius * 2, center_y + radius), fill=fill)
        draw.polygon([(center_x - radius * 2, center_y), (center_x + radius * 2, center_y), (center_x, center_y + size)], fill=fill)

    def _remote_image(self, url: str) -> Image.Image | None:
        if not url.startswith(("https://", "http://")):
            return None
        cached = self._remote_cache.get(url)
        if cached is not None:
            return cached.copy()

        candidates = self._remote_image_candidates(url)
        headers = {
            "User-Agent": "Mozilla/5.0",
            "Referer": "https://www.bilibili.com/",
            "Accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
        }
        for candidate in candidates:
            for attempt in range(3):
                try:
                    request = Request(candidate, headers=headers)
                    with urlopen(request, timeout=10) as response:
                        with Image.open(BytesIO(response.read())) as source:
                            result = source.convert("RGBA")
                    self._remote_cache[url] = result
                    return result.copy()
                except Exception:
                    if attempt < 2:
                        sleep(0.25 * (attempt + 1))
        return None

    @staticmethod
    def _remote_image_candidates(url: str) -> list[str]:
        """Prefer HTTPS and rotate Bilibili image hosts during CDN failures."""
        parsed = urlsplit(url)
        if not parsed.hostname:
            return [url]

        scheme = "https" if parsed.scheme in {"http", "https"} else parsed.scheme
        hosts = [parsed.netloc]
        hostname = parsed.hostname.lower()
        if hostname in {"i0.hdslb.com", "i1.hdslb.com", "i2.hdslb.com"}:
            port = f":{parsed.port}" if parsed.port else ""
            hosts.extend(f"{host}{port}" for host in ("i0.hdslb.com", "i1.hdslb.com", "i2.hdslb.com"))

        candidates: list[str] = []
        for host in hosts:
            candidate = urlunsplit((scheme, host, parsed.path, parsed.query, ""))
            if candidate not in candidates:
                candidates.append(candidate)
        return candidates


    @staticmethod
    def _paste_full_image(
        image: Image.Image, source: Image.Image | None, box: tuple[int, int, int, int]
    ) -> bool:
        if source is None:
            return False
        left, top, right, bottom = box
        width, height = right - left, bottom - top
        resized = source.resize((width, height), Image.Resampling.LANCZOS)
        image.alpha_composite(resized, (left, top))
        return True

    def _paste_circle(self, image: Image.Image, url: str, left: int, top: int, size: int, fallback: str) -> None:
        ImageDraw.Draw(image).ellipse((left, top, left + size, top + size), fill=fallback)
        source = self._remote_image(url)
        if source is None:
            return
        scale = max(size / source.width, size / source.height)
        resized = source.resize((round(source.width * scale), round(source.height * scale)), Image.Resampling.LANCZOS)
        x = (resized.width - size) // 2
        y = (resized.height - size) // 2
        avatar = resized.crop((x, y, x + size, y + size))
        mask = Image.new("L", (size, size), 0)
        ImageDraw.Draw(mask).ellipse((0, 0, size, size), fill=255)
        image.paste(avatar, (left, top), mask)

    def _paste_emoji(self, image: Image.Image, url: str, left: int, top: int, size: int) -> None:
        source = self._remote_image(url)
        if source is None:
            ImageDraw.Draw(image).rounded_rectangle((left, top, left + size, top + size), radius=12, fill="#eceaf2")
            return
        scale = min(size / source.width, size / source.height)
        resized = source.resize((max(1, round(source.width * scale)), max(1, round(source.height * scale))), Image.Resampling.LANCZOS)
        x = left + (size - resized.width) // 2
        y = top + (size - resized.height) // 2
        image.alpha_composite(resized, (x, y))

    @staticmethod
    def _qr_image(url: str, size: int) -> Image.Image | None:
        try:
            qr = qrcode.QRCode(version=None, box_size=8, border=2)
            qr.add_data(url)
            qr.make(fit=True)
            return qr.make_image(fill_color="#252733", back_color="#ffffff").convert("RGBA").resize((size, size), Image.Resampling.NEAREST)
        except Exception:
            return None

    @staticmethod
    def _format_stat(value: str | None) -> str:
        try:
            number = int(str(value or "0"))
        except ValueError:
            return "--"
        if number >= 10_000:
            return f"{number / 10_000:.1f}".rstrip("0").rstrip(".") + "万"
        return str(number)

    def select_schedule_sticker(self, hosts: Iterable[str]) -> Path | None:
        """Choose one local sticker belonging to the scheduled hosts."""
        stickers = self._sticker_map()
        candidates = [path for host in hosts for path in stickers.get(str(host), [])]
        return random.choice(candidates) if candidates else None

    def _sticker_map(self) -> dict[str, list[Path]]:
        if self._stickers is not None:
            return self._stickers
        result: dict[str, list[Path]] = {}
        if self.sticker_dir.is_dir():
            for directory in self.sticker_dir.iterdir():
                if directory.is_dir():
                    result[directory.name] = [path for path in directory.glob("*.png") if path.is_file()]
        self._stickers = result
        return result

    @staticmethod
    def _paste_sticker(image: Image.Image, path: Path, left: int, top: int, width: int, height: int) -> None:
        try:
            with Image.open(path) as source:
                sticker = source.convert("RGBA")
                sticker.thumbnail((width, height), Image.Resampling.LANCZOS)
                x = left + (width - sticker.width) // 2
                y = top + height - sticker.height
                image.alpha_composite(sticker, (x, y))
        except OSError:
            return

    def _font(self, size: int, bold: bool = False) -> ImageFont.ImageFont:
        key = (size, bold)
        if key in self._fonts:
            return self._fonts[key]
        candidates: list[Path] = []
        if self.font_path:
            candidates.append(self.font_path)
        candidates.append(self.sticker_dir / "font.ttf")
        candidates.extend(
            [
                Path(r"C:\Windows\Fonts\msyhbd.ttc" if bold else r"C:\Windows\Fonts\msyh.ttc"),
                Path(r"C:\Windows\Fonts\simhei.ttf"),
                Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"),
                Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
            ]
        )
        for candidate in candidates:
            try:
                if candidate.is_file():
                    font = ImageFont.truetype(str(candidate), size=size)
                    self._fonts[key] = font
                    return font
            except OSError:
                continue
        font = ImageFont.load_default(size=size)
        self._fonts[key] = font
        return font

    @staticmethod
    def _text_width(text: str, font: ImageFont.ImageFont) -> int:
        box = font.getbbox(text)
        return box[2] - box[0]

    @staticmethod
    def _line_height(font: ImageFont.ImageFont) -> int:
        box = font.getbbox("Ag")
        return max(1, box[3] - box[1])

    def _wrap(self, text: str, font: ImageFont.ImageFont, width: int, maximum: int) -> list[str]:
        value = " ".join(str(text).split()) or " "
        lines: list[str] = []
        current = ""
        for char in value:
            candidate = current + char
            if current and self._text_width(candidate, font) > width:
                lines.append(current)
                current = char
            else:
                current = candidate
        if current:
            lines.append(current)
        if len(lines) <= maximum:
            return lines
        return lines[: maximum - 1] + [self._ellipsize(lines[maximum - 1], font, width)]

    def _wrap_preserving_linebreaks(
        self,
        text: str,
        font: ImageFont.ImageFont,
        width: int,
        maximum: int | None,
    ) -> list[str]:
        lines: list[str] = []
        for paragraph in str(text).replace("\r\n", "\n").replace("\r", "\n").split("\n"):
            wrapped = self._wrap(paragraph or " ", font, width, maximum or 1_000_000)
            for line in wrapped:
                if maximum is not None and len(lines) == maximum:
                    return lines[: maximum - 1] + [self._ellipsize(lines[maximum - 1], font, width)]
                lines.append(line)
        return lines

    def _ellipsize(self, text: str, font: ImageFont.ImageFont, width: int) -> str:
        if self._text_width(text, font) <= width:
            return text
        value = text
        while value and self._text_width(value + "...", font) > width:
            value = value[:-1]
        return value.rstrip() + "..."

    def _draw_centered(
        self,
        draw: ImageDraw.ImageDraw,
        center_x: int,
        center_y: int,
        text: str,
        font: ImageFont.ImageFont,
        fill: str,
    ) -> None:
        box = draw.textbbox((0, 0), text, font=font)
        draw.text((center_x - (box[2] - box[0]) // 2, center_y - (box[3] - box[1]) // 2 - box[1]), text, font=font, fill=fill)

    def _save(self, image: Image.Image, prefix: str) -> Path:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        path = self.output_dir / f"{prefix}_{time_ns()}.png"
        transparent_rounded_corners(image).save(path, format="PNG", optimize=True)
        return path
